#!/usr/bin/env ruby
require_relative 'lib/parse_arguments'


command = ARGV[0]
options = ParseArguments.parse
options[:name] = ARGV[1]
error_messages = ParseArguments.validate(options)

if error_messages.empty?
  puts "Theoretically creating: I drank #{options[:ounces]} oz of #{options[:name]}, which is a #{options[:style]} style beer, costing me $#{options[:cost]}"
else
  puts error_messages
end